final_project:
  target: dev
  outputs:
    dev:
      project: final-project-382415
      dataset: crime_final_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../keys/final-project-382415-972971564a58.json
      location: us
      method: service-account
      priority: interactive
      threads: 1
      type: bigquery
