final_project:
  target: dev
  outputs:
    dev:
      project: [YOUR PROJECT ID]
      dataset: dataset_analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: ../credentials/credentials.json
      location: us
      method: service-account
      priority: interactive
      threads: 1
      type: bigquery
